### ISSUE TITLE
`Encountered unknown tag` when building

### ISSUE THREAD

**Issue by TeddyHuang-00** [pelican-plugins/liquid-tags#27]
Python: 3.10.8
Pelican: 4.8.0
liquid-tags: 1.0.3

Plugins that I enabled:
```py
PLUGINS = [
    "pelican.plugins.liquid_tags.notebook",
    "pelican.plugins.liquid_tags.include_code",
    "pelican.plugins.jinja_filters",
    "pelican.plugins.jinja2content",
    "pelican.plugins.simple_footnotes",
    "pelican.plugins.render_math",
    "pelican.plugins.webassets",
    "minify",
]
```

Accordingly liquid tags:
```py
LIQUID_TAGS = [
    "notebook",
    "include_code",
]
```

And then I created `code` subfolder under `content`, and add this line to a post
```jinja
{% include_code test.py %}
```

when building such content, pelican raised an warning that:
```sh
Could not process Cate/test-post.md
Encountered unknown tag 'include_code'.
```

And I've tested on several other tags, and none of them would work. Really don't have an idea about what's going wrong

**Comment by TeddyHuang-00** [comment]
Ah, I located the problem of being conflicted with "pelican.plugins.jinja2content". This is not what I would expect. Perhaps some bug fixes are needed here?

**Comment by TeddyHuang-00** [comment]
Alternatively, if liquid-tags could provide a raw `include` seems to solve most of the problem as one could avoid using jinja2content

**Comment by mirekdlugosz** [comment]
The problem is that liquid tags uses `{% tag %}` syntax, which is also valid Jinja2 syntax.

jinja2content processes files first. It will read file and consider it to be a Jinja2 template. After rendering a template, it will then pass the content to specific file reader. This is the place where liquid tags would kick in. In other words, you need to ensure that liquid tags can handle content **after** being processed by Jinja2 - and that Jinja2 does not touch the content intended for liquid tags.

This can be done with [escaping](https://jinja.palletsprojects.com/en/3.1.x/templates/#escaping). I did a quick test and following appears to work as expected - Jinja2 produces liquid tag syntax, which is then replaced by actual HTML when writing a file:

```
{% raw %}{% youtube dQw4w9WgXcQ %}{% endraw %}
```

For the record, there's also fundamentally the same issue reported in [jinja2content bug tracker](https://github.com/pelican-plugins/jinja2content/issues/4).

I'm going to add a short note about this incompatibility and fix to README file, but other than that, I am not sure what should be done about this.

**Comment by TeddyHuang-00** [comment]
Problem solved, huge thanks!
